name: Run tests and publish report

on:
  push:
    branches: [ "main", "dev", "ci-pipeline" ]
  pull_request:
    branches: [ "main", "dev", "ci-pipeline" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Setup JDK for Allure
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      # Backend setup and tests
      - name: Backend Tests
        run: |
          cd backend
          npm ci
          java -jar target/demo-0.0.1-SNAPSHOT.jar &
          sleep 20 
          npm test
        continue-on-error: true

      # Frontend setup and tests
      - name: Frontend Tests
        run: |
          cd frontend
          npm ci
          npx playwright install --with-deps
          npm test
        continue-on-error: true

      - name: Debug directories
        run: |
          echo "Backend directory contents:"
          ls -la backend
          echo "Frontend directory contents:"
          ls -la frontend
          echo "gh-pages directory contents:"
          ls -la gh-pages

      # Load Allure report history
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Build combined Allure report
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: |
            backend/allure-results
            frontend/allure-results

      # Publish Allure report to GitHub Pages
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages/allure-history

